"""empty message

Revision ID: 6a2721cc054f
Revises: 
Create Date: 2023-11-19 11:55:55.846880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a2721cc054f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolist',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('priority_max', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('todoitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.String(), nullable=True),
    sa.Column('priority', sa.Float(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('priority_update_algorithm', sa.Integer(), nullable=True),
    sa.Column('priority_update_increment_weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['todolist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todoitem')
    op.drop_table('todolist')
    # ### end Alembic commands ###
