"""empty message

Revision ID: 9992d6e323ad
Revises: 6a2721cc054f
Create Date: 2023-12-01 18:45:40.645329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9992d6e323ad'
down_revision: Union[str, None] = '6a2721cc054f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todoitem', sa.Column('priority_update_deadline', sa.DateTime(), nullable=True))
    op.add_column('todoitem', sa.Column('priority_update_deadline_max_priority', sa.Float(), nullable=True))
    op.add_column('todoitem', sa.Column('last_priority_update', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todoitem', 'last_priority_update')
    op.drop_column('todoitem', 'priority_update_deadline_max_priority')
    op.drop_column('todoitem', 'priority_update_deadline')
    # ### end Alembic commands ###
